version: '2.1'

services:
    nginx:
        image: nginx:1
        volumes:
            - .:/srv:ro
            - ./docker/nginx/dev.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - php

    php:
        build: docker/php
        image: mykiwi/symfony-db:7.0-fpm
        working_dir: /srv
        volumes:
            - .:/srv
        depends_on:
            mariadb:
                condition: 'service_healthy'
            mysql:
                condition: 'service_healthy'
            pgsql:
                condition: 'service_healthy'

    mariadb:
        image: mariadb:10.1
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
        healthcheck:
            test: mysql --user=root --password='' --execute "show databases"
            interval: 1s
            timeout:  1s
            retries:  20

    mysql:
        image: mysql:5.7
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        healthcheck:
            test: mysql --user=root --password='' --execute "show databases"
            interval: 1s
            timeout:  1s
            retries:  20

    pgsql:
        image: postgres:9.6-alpine
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=pass
        healthcheck:
            test: psql postgresql://user:pass@localhost --list
            interval: 1s
            timeout:  1s
            retries:  20
