version: '2'

services:
    nginx:
        image: nginx:1-alpine
        volumes:
            - .:/srv:ro
            - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
        links:
            - php

    php:
        build: docker/php
        image: mykiwi/symfony-db:7.0-fpm
        volumes:
            - .:/srv
            - /srv/var/cache
            - /srv/var/logs
            - /srv/var/sessions
        environment:
            - SYMFONY_ENV=dev
        links:
            - mysql
            - pgsql

    mariadb:
        image: mariadb:10.1
        environment:
            - MYSQL_USER=user
            - MYSQL_PASSWORD=pass

    mysql:
        image: mysql:8.0
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - MYSQL_USER=user
            - MYSQL_PASSWORD=pass

    pgsql:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=pass
