install:
  - sudo apt-get install -y linux-image-virtual kernel linux-image-extra-virtual
  - curl -sSL https://get.docker.com/ | sudo sh
  - sudo pip install docker-compose

script:
  - docker --version
  - docker-compose --version
  - make

