version: '2.1'

services:
    app:
        build: docker/php
        image: mykiwi/symfony-base:7.0-fpm
        working_dir: /srv
        volumes:
            - .:/srv
        command: ./bin/console server:run 0.0.0.0:8000
